// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.8
// source: ticket.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Ticket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator  string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Note     string `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Variable string `protobuf:"bytes,4,opt,name=variable,proto3" json:"variable,omitempty"`
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *Ticket) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ticket) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Ticket) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Ticket) GetVariable() string {
	if x != nil {
		return x.Variable
	}
	return ""
}

type TicketID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TicketID) Reset() {
	*x = TicketID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketID) ProtoMessage() {}

func (x *TicketID) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketID.ProtoReflect.Descriptor instead.
func (*TicketID) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *TicketID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TicketRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Low  int64 `protobuf:"varint,1,opt,name=low,proto3" json:"low,omitempty"`
	High int64 `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
}

func (x *TicketRange) Reset() {
	*x = TicketRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketRange) ProtoMessage() {}

func (x *TicketRange) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketRange.ProtoReflect.Descriptor instead.
func (*TicketRange) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *TicketRange) GetLow() int64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *TicketRange) GetHigh() int64 {
	if x != nil {
		return x.High
	}
	return 0
}

var File_ticket_proto protoreflect.FileDescriptor

var file_ticket_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x06, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x0b, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x32, 0xa1, 0x02, 0x0a, 0x0a, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e, 0x0a, 0x0c, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x12, 0x2b, 0x0a, 0x09, 0x67, 0x65, 0x74,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x31, 0x0a, 0x0a, 0x67, 0x65, 0x74, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x30, 0x01, 0x12, 0x3d, 0x0a, 0x0c, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x28, 0x01, 0x12, 0x44, 0x0a, 0x11, 0x67, 0x65, 0x74, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x42, 0x79, 0x4f, 0x6e, 0x65, 0x12, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x0d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ticket_proto_rawDescOnce sync.Once
	file_ticket_proto_rawDescData = file_ticket_proto_rawDesc
)

func file_ticket_proto_rawDescGZIP() []byte {
	file_ticket_proto_rawDescOnce.Do(func() {
		file_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(file_ticket_proto_rawDescData)
	})
	return file_ticket_proto_rawDescData
}

var file_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ticket_proto_goTypes = []interface{}{
	(*Ticket)(nil),                 // 0: proto.Ticket
	(*TicketID)(nil),               // 1: proto.TicketID
	(*TicketRange)(nil),            // 2: proto.TicketRange
	(*wrapperspb.StringValue)(nil), // 3: google.protobuf.StringValue
}
var file_ticket_proto_depIdxs = []int32{
	0, // 0: proto.TicketInfo.createTicket:input_type -> proto.Ticket
	1, // 1: proto.TicketInfo.getTicket:input_type -> proto.TicketID
	2, // 2: proto.TicketInfo.getTickets:input_type -> proto.TicketRange
	0, // 3: proto.TicketInfo.updateTicket:input_type -> proto.Ticket
	3, // 4: proto.TicketInfo.getTicketOneByOne:input_type -> google.protobuf.StringValue
	1, // 5: proto.TicketInfo.createTicket:output_type -> proto.TicketID
	0, // 6: proto.TicketInfo.getTicket:output_type -> proto.Ticket
	0, // 7: proto.TicketInfo.getTickets:output_type -> proto.Ticket
	3, // 8: proto.TicketInfo.updateTicket:output_type -> google.protobuf.StringValue
	0, // 9: proto.TicketInfo.getTicketOneByOne:output_type -> proto.Ticket
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ticket_proto_init() }
func file_ticket_proto_init() {
	if File_ticket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ticket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ticket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ticket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ticket_proto_goTypes,
		DependencyIndexes: file_ticket_proto_depIdxs,
		MessageInfos:      file_ticket_proto_msgTypes,
	}.Build()
	File_ticket_proto = out.File
	file_ticket_proto_rawDesc = nil
	file_ticket_proto_goTypes = nil
	file_ticket_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TicketInfoClient is the client API for TicketInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TicketInfoClient interface {
	CreateTicket(ctx context.Context, in *Ticket, opts ...grpc.CallOption) (*TicketID, error)
	GetTicket(ctx context.Context, in *TicketID, opts ...grpc.CallOption) (*Ticket, error)
	GetTickets(ctx context.Context, in *TicketRange, opts ...grpc.CallOption) (TicketInfo_GetTicketsClient, error)
	UpdateTicket(ctx context.Context, opts ...grpc.CallOption) (TicketInfo_UpdateTicketClient, error)
	GetTicketOneByOne(ctx context.Context, opts ...grpc.CallOption) (TicketInfo_GetTicketOneByOneClient, error)
}

type ticketInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketInfoClient(cc grpc.ClientConnInterface) TicketInfoClient {
	return &ticketInfoClient{cc}
}

func (c *ticketInfoClient) CreateTicket(ctx context.Context, in *Ticket, opts ...grpc.CallOption) (*TicketID, error) {
	out := new(TicketID)
	err := c.cc.Invoke(ctx, "/proto.TicketInfo/createTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketInfoClient) GetTicket(ctx context.Context, in *TicketID, opts ...grpc.CallOption) (*Ticket, error) {
	out := new(Ticket)
	err := c.cc.Invoke(ctx, "/proto.TicketInfo/getTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketInfoClient) GetTickets(ctx context.Context, in *TicketRange, opts ...grpc.CallOption) (TicketInfo_GetTicketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TicketInfo_serviceDesc.Streams[0], "/proto.TicketInfo/getTickets", opts...)
	if err != nil {
		return nil, err
	}
	x := &ticketInfoGetTicketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TicketInfo_GetTicketsClient interface {
	Recv() (*Ticket, error)
	grpc.ClientStream
}

type ticketInfoGetTicketsClient struct {
	grpc.ClientStream
}

func (x *ticketInfoGetTicketsClient) Recv() (*Ticket, error) {
	m := new(Ticket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ticketInfoClient) UpdateTicket(ctx context.Context, opts ...grpc.CallOption) (TicketInfo_UpdateTicketClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TicketInfo_serviceDesc.Streams[1], "/proto.TicketInfo/updateTicket", opts...)
	if err != nil {
		return nil, err
	}
	x := &ticketInfoUpdateTicketClient{stream}
	return x, nil
}

type TicketInfo_UpdateTicketClient interface {
	Send(*Ticket) error
	CloseAndRecv() (*wrapperspb.StringValue, error)
	grpc.ClientStream
}

type ticketInfoUpdateTicketClient struct {
	grpc.ClientStream
}

func (x *ticketInfoUpdateTicketClient) Send(m *Ticket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ticketInfoUpdateTicketClient) CloseAndRecv() (*wrapperspb.StringValue, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(wrapperspb.StringValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ticketInfoClient) GetTicketOneByOne(ctx context.Context, opts ...grpc.CallOption) (TicketInfo_GetTicketOneByOneClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TicketInfo_serviceDesc.Streams[2], "/proto.TicketInfo/getTicketOneByOne", opts...)
	if err != nil {
		return nil, err
	}
	x := &ticketInfoGetTicketOneByOneClient{stream}
	return x, nil
}

type TicketInfo_GetTicketOneByOneClient interface {
	Send(*wrapperspb.StringValue) error
	Recv() (*Ticket, error)
	grpc.ClientStream
}

type ticketInfoGetTicketOneByOneClient struct {
	grpc.ClientStream
}

func (x *ticketInfoGetTicketOneByOneClient) Send(m *wrapperspb.StringValue) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ticketInfoGetTicketOneByOneClient) Recv() (*Ticket, error) {
	m := new(Ticket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TicketInfoServer is the server API for TicketInfo service.
type TicketInfoServer interface {
	CreateTicket(context.Context, *Ticket) (*TicketID, error)
	GetTicket(context.Context, *TicketID) (*Ticket, error)
	GetTickets(*TicketRange, TicketInfo_GetTicketsServer) error
	UpdateTicket(TicketInfo_UpdateTicketServer) error
	GetTicketOneByOne(TicketInfo_GetTicketOneByOneServer) error
}

// UnimplementedTicketInfoServer can be embedded to have forward compatible implementations.
type UnimplementedTicketInfoServer struct {
}

func (*UnimplementedTicketInfoServer) CreateTicket(context.Context, *Ticket) (*TicketID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTicket not implemented")
}
func (*UnimplementedTicketInfoServer) GetTicket(context.Context, *TicketID) (*Ticket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTicket not implemented")
}
func (*UnimplementedTicketInfoServer) GetTickets(*TicketRange, TicketInfo_GetTicketsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTickets not implemented")
}
func (*UnimplementedTicketInfoServer) UpdateTicket(TicketInfo_UpdateTicketServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateTicket not implemented")
}
func (*UnimplementedTicketInfoServer) GetTicketOneByOne(TicketInfo_GetTicketOneByOneServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTicketOneByOne not implemented")
}

func RegisterTicketInfoServer(s *grpc.Server, srv TicketInfoServer) {
	s.RegisterService(&_TicketInfo_serviceDesc, srv)
}

func _TicketInfo_CreateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ticket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketInfoServer).CreateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TicketInfo/CreateTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketInfoServer).CreateTicket(ctx, req.(*Ticket))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketInfo_GetTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketInfoServer).GetTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TicketInfo/GetTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketInfoServer).GetTicket(ctx, req.(*TicketID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketInfo_GetTickets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TicketRange)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TicketInfoServer).GetTickets(m, &ticketInfoGetTicketsServer{stream})
}

type TicketInfo_GetTicketsServer interface {
	Send(*Ticket) error
	grpc.ServerStream
}

type ticketInfoGetTicketsServer struct {
	grpc.ServerStream
}

func (x *ticketInfoGetTicketsServer) Send(m *Ticket) error {
	return x.ServerStream.SendMsg(m)
}

func _TicketInfo_UpdateTicket_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TicketInfoServer).UpdateTicket(&ticketInfoUpdateTicketServer{stream})
}

type TicketInfo_UpdateTicketServer interface {
	SendAndClose(*wrapperspb.StringValue) error
	Recv() (*Ticket, error)
	grpc.ServerStream
}

type ticketInfoUpdateTicketServer struct {
	grpc.ServerStream
}

func (x *ticketInfoUpdateTicketServer) SendAndClose(m *wrapperspb.StringValue) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ticketInfoUpdateTicketServer) Recv() (*Ticket, error) {
	m := new(Ticket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TicketInfo_GetTicketOneByOne_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TicketInfoServer).GetTicketOneByOne(&ticketInfoGetTicketOneByOneServer{stream})
}

type TicketInfo_GetTicketOneByOneServer interface {
	Send(*Ticket) error
	Recv() (*wrapperspb.StringValue, error)
	grpc.ServerStream
}

type ticketInfoGetTicketOneByOneServer struct {
	grpc.ServerStream
}

func (x *ticketInfoGetTicketOneByOneServer) Send(m *Ticket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ticketInfoGetTicketOneByOneServer) Recv() (*wrapperspb.StringValue, error) {
	m := new(wrapperspb.StringValue)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TicketInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TicketInfo",
	HandlerType: (*TicketInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createTicket",
			Handler:    _TicketInfo_CreateTicket_Handler,
		},
		{
			MethodName: "getTicket",
			Handler:    _TicketInfo_GetTicket_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getTickets",
			Handler:       _TicketInfo_GetTickets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "updateTicket",
			Handler:       _TicketInfo_UpdateTicket_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "getTicketOneByOne",
			Handler:       _TicketInfo_GetTicketOneByOne_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ticket.proto",
}
