apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample-scheduler
spec:
  selector:
    matchLabels:
      app: sample-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-scheduler
    spec:
      schedulerName: sample-scheduler
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
