# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ticket.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cticket.proto\x12\x05proto\"E\n\x06Ticket\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07\x63reator\x18\x02 \x01(\t\x12\x0c\n\x04note\x18\x03 \x01(\t\x12\x10\n\x08variable\x18\x04 \x01(\t\"\x16\n\x08TicketID\x12\n\n\x02id\x18\x01 \x01(\x03\"(\n\x0bTicketRange\x12\x0b\n\x03low\x18\x01 \x01(\x03\x12\x0c\n\x04high\x18\x02 \x01(\x03\x32\x9c\x01\n\nTicketInfo\x12.\n\x0c\x63reateTicket\x12\r.proto.Ticket\x1a\x0f.proto.TicketID\x12+\n\tgetTicket\x12\x0f.proto.TicketID\x1a\r.proto.Ticket\x12\x31\n\ngetTickets\x12\x12.proto.TicketRange\x1a\r.proto.Ticket0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ticket_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TICKET']._serialized_start=23
  _globals['_TICKET']._serialized_end=92
  _globals['_TICKETID']._serialized_start=94
  _globals['_TICKETID']._serialized_end=116
  _globals['_TICKETRANGE']._serialized_start=118
  _globals['_TICKETRANGE']._serialized_end=158
  _globals['_TICKETINFO']._serialized_start=161
  _globals['_TICKETINFO']._serialized_end=317
# @@protoc_insertion_point(module_scope)
